name: Main workflow
on:
  push:
    branches:
      - main
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: setup java jdk
      uses: actions/setup-java@v2
      with:
        distribution: "temurin"
        java-version: "11"

    - name: Install Flyway
      run: |
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        tar -xzf flyway-commandline.tar.gz
        sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway

    - name: Run Flyway migrations
      run: flyway migrate -locations=filesystem:sql/migrations
      env:
        FLYWAY_URL: "jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
        FLYWAY_USER: ${{ secrets.DB_USER }}
        FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Display migrations history
      run: |
        psql -h ${{ secrets.DB_HOST }} \
             -p ${{ secrets.DB_PORT }} \
             -d ${{ secrets.DB_NAME }} \
             -U ${{ secrets.DB_USER }} \
             -c "SELECT * FROM flyway_schema_history LIMIT 100;"
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Display products that have been sold in the last 7 days
      run: |
        psql -h ${{ secrets.DB_HOST }} \
             -p ${{ secrets.DB_PORT }} \
             -d ${{ secrets.DB_NAME }} \
             -U ${{ secrets.DB_USER }} \
             -c "SELECT o.date_created, SUM(op.quantity) FROM orders AS o JOIN order_product AS op ON o.id = op.order_id WHERE o.status = 'shipped' AND o.date_created > NOW() - INTERVAL '7 DAY' GROUP BY o.date_created;"
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
