name: Apply FlyWay migration

on:
  push:
    branches:
      - main
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout the repository
        uses: actions/checkout@v2

      - name: setup java jdk
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Flyway
        run: |
          curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
          tar -xzf flyway-commandline.tar.gz
          sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway

      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run Flyway migrations
        run: flyway migrate -locations=filesystem:sql/migrations
        env:
          FLYWAY_URL: "jdbc:postgresql://localhost:5432/testdb"
          FLYWAY_USER: testuser
          FLYWAY_PASSWORD: testpassword

      - name: Install PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Display migration history
        run: psql -h localhost -p 5432 -d testdb -U testuser -c "SELECT * FROM flyway_schema_history LIMIT 100;"
        env:
          PGPASSWORD: testpassword
